export const allAmenities = [
  'Basketball',
  'Baseball',
  'Boating',
  'Dog Park',
  'Picnic',
  'Playground',
  'Restrooms',
  'Skateboarding',
  'Swimming',
  'Tennis',
];

export const parkAmenities = [
  ['Baseball', 'Picnic', 'Playground', 'Restrooms', 'Tennis', 'Restrooms'],
  ['Dog Park', 'Playground', 'Restrooms', 'Skateboarding'],
  ['Dog Park', 'Basketball', 'Restrooms'],
  ['Playground', 'Restrooms', 'Swimming'],
  ['Skateboarding'],
  ['Basketball', 'Dog Park', 'Picnic', 'Swimming', 'Restrooms'],
  ['Dog Park', 'Picnic', 'Playground', 'Restrooms'],
  ['Baseball', 'Restrooms', 'Tennis', 'Skateboarding'],
  [
    'Playground',
    'Restrooms',
    'Skateboarding',
    'Swimming',
    'Tennis',
  ],
  ['Basketball', 'Baseball', 'Boating', 'Dog Park', 'Picnic'],
  [
    'Basketball',
    'Baseball',
    'Dog Park',
    'Picnic',
    'Playground',
    'Restrooms',
    'Swimming',
    'Tennis',
  ],
  [
    'Baseball',
    'Boating',
    'Dog Park',
    'Playground',
    'Restrooms',
    'Skateboarding',
    'Tennis',
  ],
  [
    'Basketball',
    'Boating',
    'Dog Park',
    'Picnic',
    'Playground',
    'Restrooms',
    'Swimming',
    'Tennis',
  ],
];

export const icons = {
  Baseball: '/dist/components/assets/baseball.svg',
  Basketball: '/dist/components/assets/basketball.svg',
  Boating: '/dist/components/assets/boating.svg',
  'Dog Park': '/dist/components/assets/dog.svg',
  Logo: '/dist/components/assets/SMC-logo.png',
  Marker: '/dist/components/assets/marker.png',
  Person: '/dist/components/assets/person.svg',
  Picnic: '/dist/components/assets/picnic-table.svg',
  Playground: '/dist/components/assets/playground.svg',
  Restrooms: '/dist/components/assets/restrooms.svg',
  Skateboarding: '/dist/components/assets/skateboarder.svg',
  Swimming: '/dist/components/assets/swim.svg',
  Tennis: '/dist/components/assets/tennis.svg',
  User: '/dist/components/assets/user-marker.svg',
};
