export const allAmenities = [
  'Basketball',
  'Baseball',
  'Boating',
  'Dog Park',
  'Picnic',
  'Playground',
  'Restrooms',
  'Skateboarding',
  'Swimming',
  'Tennis',
];

export const parkAmenities = [
  ['Baseball', 'Picnic', 'Playground', 'Restrooms', 'Tennis', 'Restrooms'],
  ['Dog Park', 'Playground', 'Restrooms', 'Skateboarding'],
  ['Dog Park', 'Basketball', 'Restrooms'],
  ['Playground', 'Restrooms', 'Swimming'],
  ['Skateboarding'],
  ['Basketball', 'Dog Park', 'Picnic', 'Swimming', 'Restrooms'],
  ['Dog Park', 'Picnic', 'Playground', 'Restrooms'],
  ['Baseball', 'Restrooms', 'Tennis', 'Skateboarding'],
  [
    'Playground',
    'Restrooms',
    'Skateboarding',
    'Swimming',
    'Restrooms',
    'Tennis',
  ],
  ['Basketball', 'Baseball', 'Boating', 'Dog Park', 'Picnic'],
  [
    'Basketball',
    'Baseball',
    'Dog Park',
    'Picnic',
    'Playground',
    'Restrooms',
    'Swimming',
    'Tennis',
  ],
  [
    'Baseball',
    'Boating',
    'Dog Park',
    'Playground',
    'Restrooms',
    'Skateboarding',
    'Tennis',
  ],
  [
    'Basketball',
    'Boating',
    'Dog Park',
    'Picnic',
    'Playground',
    'Restrooms',
    'Swimming',
    'Tennis',
  ],
];
